# ======================
# Vision 模块配置
# ======================
vision:
  name: "vision"
  log_path: "./logs/modules/vision.log"
  camera_list:
    camera1:
      enable: true
      name: "imx415"
      channel_list:
        channel1:
          enable: true
          name: "/dev/video33"
          bufcnt: 10
          width: 1920
          height: 1080
          fps: 30
          fmt: "NV12"
          rotation: 0
          fix_width: 640
          fix_height: 640
          fix_fmt: "rgb888"
        channel2:
          enable: false
          name: "rkisp_scard2"
          bufcnt: 10
          width: 1920
          height: 1080
          fps: 60
          fmt: "rgb888"
          rotation: 0
          # fix_width: 640
          # fix_height: 640
    camera2:
      enable: false
      name: "ov13580"
      channel_list:
        channel1:
          enable: true
          name: "rkisp_scard3"
          bufcnt: 10
          width: 1920
          height: 1080
          fps: 60
          fmt: "rgb888"
          rotation: 0
          # fix_width: 640
          # fix_height: 640

  # 全局参数
  advanced:
    max_video_duration: 3600
    debug_mode: false