base_dir: "/root/app/logs"  # 基础日志目录
global_conf:
  write_time: 3
loggers:
  vision:
    file: "module/vision.log"     # 相对于base_dir的路径
    max_size: "100MB"       # 支持KB/MB/GB单位
    max_days: 7             # 保留天数
    level: "debug"           # trace/debug/info/warn/error/critical
    rotation: "size"        # size/daily/session/none

  imx415:
    file: "module/vision.log"   
    max_size: "100MB"
    max_days: 7
    level: "debug"
    rotation: "size"

  /dev/video33:
    file: "module/vision.log"   
    max_size: "100MB"
    max_days: 7
    level: "debug"
    rotation: "size"